{% set name = "jupyter-rospkg" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_rospkg-{{ version }}.tar.gz
  sha256: 2c0379aa510ed6cf70dbc88319e79ee58e5bf2afb37c4c81c39b152f927bdfde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - jupyter_server <2,>=1.6
    - rospkg
    - notebook

test:
  imports:
    - jupyter_rospkg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jupyter-rospkg/
  summary: A server extension for JupyterLab to handle ROS packages
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
